name: Auto Docs

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: autodocs-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write  # needed for gh-pages deploy

jobs:
  build-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      APP_BASE_URL: http://localhost:5274
      CI: true
      # where Playwright browsers live (so we can cache them)
      PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            docs/package-lock.json

      - name: Install root deps
        run: npm ci || npm i

      - name: Install docs deps
        working-directory: docs
        run: npm ci || npm i

      # --- Cache Playwright browsers (Option C) ---
      - name: Resolve Playwright version
        id: pw
        shell: bash
        run: |
          PW_VERSION=$(node -p "require('@playwright/test/package.json').version")
          echo "version=$PW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ runner.os }}-${{ steps.pw.outputs.version }}

      # --- Install Chromium only (Option B) ---
      - name: Install Playwright (Chromium only)
        run: npx playwright install chromium

      # --- Start your demo app on :5274 ---
      - name: Start DEMO app on :5274
        run: |
          nohup bash -c "npm run app:start:demo" >/dev/null 2>&1 &
          npx wait-on http://localhost:5274

      # --- Crawl, generate docs, build, publish ---
      - name: Crawl & Take Screenshots
        run: npm run crawl

      - name: Generate Markdown Docs
        run: npm run docs:gen

      - name: Build Docusaurus
        working-directory: docs
        run: npm run build

      - name: Upload screenshots & map (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autodocs-output
          path: |
            docs/static/img/autoshots/**
            autoshots.map.json
            docs/docs/product-tour.md

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build